version: '2'
services:
    rest:
        build: 'REST'
        ports: 
            - '3000:3000'
        links: 
            - mongo
    spa:
        build: 'SPA'
        ports: 
            - '8000:8000'                
    mongo:
        image: mongo
        ports:
            - "27017:27017"
        command: "--smallfiles --logpath=/dev/null"